version: "3.9"

x-service:
  default: &default
    # image: ghcr.io/xjb/rails:main
    image: rails-sandbox:latest
    volumes:
      - .:/workspace
      - bundle:/usr/local/bundle
      - node_modules:/workspace/node_modules
    tmpfs:
      - /workspace/tmp/pids:uid=1000,gid=1000
      - /workspace/log:uid=1000,gid=1000
    tty: true
    stdin_open: true
    restart: unless-stopped
    logging:
      options:
        max-size: 1k

services:
  ap:
    <<: *default
    build: .
    ports:
      - "3000:3000"
    environment:
      RAILS_MASTER_KEY:
      SECRET_KEY_BASE:
    #   SELENIUM_HUB_URL: http://hub:4444/wd/hub
    #   # SELENIUM_HEADLESS: "false"

  debug:
    <<: *default
    entrypoint: rdebug-ide --host 0.0.0.0 --port 1234 --
    command: ["bin/rails", "server", "-b", "0.0.0.0"]
    ports:
      - "3000:3000"
      - "1234:1234"
    environment:
      RAILS_MASTER_KEY:
      SECRET_KEY_BASE:
    profiles: [debug]

  webpack:
    <<: *default
    entrypoint: ""
    command: ./bin/webpack-dev-server
    ports:
      - "3035:3035"

  rubocop:
    <<: *default
    entrypoint: ""
    command: sudo -E bundle exec rubocop-daemon start --no-daemon --binding 0.0.0.0 --port 3001
    ports:
      - "3001:3001"
    volumes:
      - ./.rubocop-daemon:/home/app/.cache/rubocop-daemon/workspace
      - .:/workspace
      - bundle:/usr/local/bundle
    logging:
      driver: none

  hub:
    image: selenium/standalone-chrome:4.1.2
    ports:
      - "7900:7900"
    environment:
      VNC_NO_PASSWORD: 1
    profiles: [test]

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:alpine
    # ports:
    #   - "6379:6379"
    # volumes:
    #   - "./data/redis:/data"

  worker:
    <<: *default
    entrypoint: ""
    command: bundle exec sidekiq
    # command: bundle exec sidekiq -C config/sidekiq.yml
    links:
      - redis

volumes:
  bundle:
  node_modules:
