version: "3.9"
services:
  ap:
    image: ghcr.io/xjb/rails:main
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace
      - bundle:/usr/local/bundle
      - node_modules:/workspace/node_modules
    tty: true
    stdin_open: true

  webpack:
    image: ghcr.io/xjb/rails:main
    entrypoint: ""
    command: ./bin/webpack-dev-server
    volumes:
      - .:/workspace
      - bundle:/usr/local/bundle
      - node_modules:/workspace/node_modules

volumes:
  bundle:
  node_modules:
