# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies, and  run linters
name: Rails - Install dependencies and run linters

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      # Add or Replace any other security checks here
      - name: Run security checks
        run: |
          bundle exec bundler-audit --update
          bundle exec brakeman -q -w2
      # Add or Replace any other Linters here
      - name: Run linters
        run: |
          bundle exec rubocop --parallel
      - name: Run ERB linters
        run: |
          bundle exec erblint --lint-all

  db-seed:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rails-env: ['production', 'test', 'development']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run db:seed
        env:
          RAILS_ENV: ${{ matrix.rails-env }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          bundle exec rails db:migrate:reset db:seed
